/* eslint-env es6 */

export const queriesNames = {
  "admin-group-list": "admin-group-list",
  "advertiser-channels": "advertiser-channels",
  "advertiser-details": "advertiser-details",
  "advertiser-industries": "advertiser-industries",
  "advertisers-list": "advertisers-list",
  "asset-list": "asset-list",
  "asset-list-infinite": "asset-list-infinite",
  "audience-set-strategy-list": "audience-set-strategy-list",
  "audience-set-strategy-list-infinite": "audience-set-strategy-list-infinite",
  "audience-sets": "audience-sets",
  "audience-sets-infinite": "audience-sets-infinite",
  "audiences-list": "audiences-list",
  "campaign-summary": "campaign-summary",
  "campaigns-list": "campaigns-list",
  "creatives-list": "creatives-list",
  "creatives-list-infinite": "creatives-list-infinite",
  credits: "credits",
  "credits-summary": "credits-summary",
  "export-ad-groups": "export-ad-groups",
  "export-campaigns": "export-campaigns",
  "export-creatives": "export-creatives",
  "export-inventory": "export-inventory",
  "export-strategy": "export-strategy",
  "get-asset": "get-asset",
  "get-asset-campaigns": "get-asset-campaigns",
  "get-asset-metrics": "get-asset-metrics",
  "get-asset-strategy-names": "get-asset-strategy-names",
  "global-messages": "global-messages",
  "market-has-asset": "market-has-asset",
  "market-has-audience-set": "market-has-audience-set",
  "metrics-graph": "metrics-graph",
  "performance-metrics": "performance-metrics",
  "profile-account": "profile-account",
  "rates-list": "rates-list",
  "reporting-ad-groups": "reporting-ad-groups",
  "reporting-ad-groups-aggregated": "reporting-ad-groups-aggregated",
  "reporting-ad-groups-performance-stats":
    "reporting-ad-groups-performance-stats",
  "reporting-campaigns": "reporting-campaigns",
  "reporting-campaigns-aggregated": "reporting-campaigns-aggregated",
  "reporting-campaigns-performance-stats":
    "reporting-campaigns-performance-stats",
  "reporting-channel-spend": "reporting-channel-spend",
  "reporting-creatives": "reporting-creatives",
  "reporting-current-campaigns": "reporting-current-campaigns",
  "reporting-inventory": "reporting-inventory",
  "reporting-inventory-aggregated": "reporting-inventory-aggregated",
  "reporting-inventory-subrows": "reporting-inventory-subrows",
  "reporting-performance-stats": "reporting-performance-stats",
  "reporting-top-ad-groups": "reporting-top-ad-groups",
  "reporting-top-channels": "reporting-top-channels",
  "single-audience-set": "single-audience-set",
  "strategy-audience-sets-list": "strategy-audience-sets-list",
  "strategy-audience-sets-list-no-pagination":
    "strategy-audience-sets-list-no-pagination",
  "strategy-campaign": "strategy-campaign",
  "strategy-campaign-ad-group-groups": "strategy-campaign-ad-group-groups",
  "strategy-campaign-ad-groups": "strategy-campaign-ad-groups",
  "strategy-changesets": "strategy-changesets",
  "strategy-creatives-list": "strategy-creatives-list",
  "strategy-creatives-list-infinite": "strategy-creatives-list-infinite",
  "strategy-draft": "strategy-draft",
  "strategy-history-chart": "strategy-history-chart",
  "strategy-line-item": "strategy-line-item",
  "strategy-list": "strategy-list",
  "strategy-summary": "strategy-summary",
  "user-countries": "user-countries",
  "user-list": "user-list",
};
